/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class menu_dompet extends javax.swing.JFrame {
    static Dompet d = new Dompet(null, null, null, null, 0, null);
    /**
     * Creates new form menu_dompet
     */
    public menu_dompet() {
        initComponents();
        MyDB db = new MyDB();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tsaldo = new javax.swing.JTextField();
        ckategori = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bKembali = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(166, 215, 232));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nama", "kategori", "saldo"
            }
        ));
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelData);

        jPanel2.setBackground(new java.awt.Color(25, 55, 109));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Saldo");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kategori");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manajemen Dompet");

        tsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsaldoActionPerformed(evt);
            }
        });
        tsaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tsaldoKeyPressed(evt);
            }
        });

        ckategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dompet", "Debit", "Kredit", "Tabungan", "Simpanan", "Deposit", "Hutang", "Aset", "Gaji", "Hadiah", "Harta Karun" }));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");

        bKembali.setActionCommand("Kembali");
        bKembali.setBackground(new java.awt.Color(153, 153, 255));
        bKembali.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        bKembali.setForeground(new java.awt.Color(0, 0, 0));
        bKembali.setLabel("Kembali");
        bKembali.setName("mlogout"); // NOI18N
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckategori, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton3))
                                .addComponent(bKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel4))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
   
        if(!Main.isNumeric(tsaldo.getText())){
            JOptionPane.showMessageDialog(rootPane, "Masukkan saldo dalam format angka!");
            return;
        }
        int Jumlah = Integer.parseInt(tsaldo.getText());
        
        if (Jumlah<=1){
            JOptionPane.showMessageDialog(rootPane, "Saldo tidak boleh kurang dari RP.1");
            return;
        }
        if(tnama.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Masukkan data nama!");
            return;
        }
        String nama = tnama.getText();
        int saldo = Integer.parseInt(tsaldo.getText());
        String kategori = ckategori.getSelectedItem().toString();
        String idmatauang = "IDR";
        String iduser = Main.idlogin;
        MyDB.insertDompet( nama,  kategori,  idmatauang,  saldo,  iduser);
        tampil();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    static int row; 
    
    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        // TODO add your handling code here:
        row = tabelData.getSelectedRow();
        Dompet g = Main.listdompet.get(row);
        tnama.setText(g.getNama());      
        tsaldo.setText(Integer.toString(g.getSaldo()));
        String jenis = g.getJenis();
        if("Dompet".equals(jenis)){ ckategori.setSelectedItem(ckategori.getItemAt(0)); }
        else if("Debit".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(1)); }
        else if("Kredit".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(2)); }
        else if("Tabungan".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(3)); }
        else if("Simpanan".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(4)); }
        else if("Deposit".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(5)); }
        else if("Hutang".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(6)); }
        else if("Aset".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(7)); }
        else if("Gaji".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(8)); }
        else if("Hadiah".equals(jenis)) {  ckategori.setSelectedItem(ckategori.getItemAt(9)); }
        else if("Harta Karun".equals(jenis)) { ckategori.setSelectedItem(ckategori.getItemAt(10)); }
        
        
       // int now = GoalGUI.ListGoal.get(row).getSaldo();
        //sisa.setText(Integer.toString(GoalGUI.ListGoal.get(row).getTarget() - now));
    }//GEN-LAST:event_tabelDataMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        new menu_user().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int Jumlah = Integer.parseInt(tsaldo.getText());
        
        if (Jumlah<=1){
            JOptionPane.showMessageDialog(rootPane, "Saldo tidak boleh kurang dari RP.1");
        }
        else{        // TODO add your handling code here:
        String nama, jenis, idmatauang, ibKembali, iduser, id;
        nama = tnama.getText();
        jenis = ckategori.getSelectedItem().toString();
        idmatauang = Main.listdompet.get(row).getIdmatauang();
        int saldo = Integer.parseInt(tsaldo.getText());
        iduser = Main.listdompet.get(row).getId_user();
        id = Main.listdompet.get(row).getId();
        MyDB.updateDompet(nama, jenis, idmatauang, saldo, iduser, id);
        tampil();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = Main.listdompet.get(row).getId();
        for(Transaksi tr: Main.listtransaksi){
            if(tr.getIduser().equals(Main.idlogin)){
                MyDB.deleteTransaksi(tr.getId());
            }          
        }
        MyDB.deleteDompet(id);
        
        tampil();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsaldoActionPerformed

    private void tsaldoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsaldoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsaldoKeyPressed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        // TODO add your handling code here:
        new menu_user().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bKembaliActionPerformed

    
    public static String totalsaldo(String id, int saldo){
        Transaksi trs = new Transaksi( null, null, null,  0,  null,  null,  null,  null);
        MyDB.move(trs);
        int s = saldo;
        for(Transaksi t: Main.listtransaksi){
            if(t.getIddompet().equals(id)){
                if(t.getKategori().equals("Pengeluaran")){
                    s = s-t.getJumlah();
                }
                else{
                    s = s+t.getJumlah();
                }
            }
        }
        String ss = Integer.toString(s);
        return ss;
    }
    
    public static void tampil(){
        MyDB.move(d);
        DefaultTableModel dtm = (DefaultTableModel) tabelData.getModel();
        dtm.setRowCount(0);
        for(Dompet d: Main.listdompet){
            dtm.addRow(new Object[]{
                d.getNama(),
                d.getJenis(),
                totalsaldo(d.getId(), d.getSaldo()),
            });            
        }
    }
    
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_dompet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_dompet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_dompet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_dompet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_dompet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button bKembali;
    private javax.swing.JComboBox<String> ckategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable tabelData;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tsaldo;
    // End of variables declaration//GEN-END:variables


}
